# Generated by Django 5.0.1 on 2024-01-20 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('password', models.CharField(max_length=234)),
                ('email', models.EmailField(max_length=235)),
                ('phone_number', models.CharField(max_length=230)),
                ('address', models.TextField(max_length=235)),
                ('login_status', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=235)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('password', models.CharField(max_length=234)),
                ('email', models.EmailField(max_length=235)),
                ('phone_number', models.CharField(max_length=230)),
                ('address', models.TextField(max_length=235)),
                ('login_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('password', models.CharField(max_length=234)),
                ('email', models.EmailField(max_length=235)),
                ('phone_number', models.CharField(max_length=230)),
                ('address', models.TextField(max_length=235)),
                ('login_status', models.BooleanField(default=False)),
                ('transport_type', models.CharField(choices=[('BS', 'BUS'), ('BE', 'BIKE'), ('TK', 'TRUCK'), ('ME', 'MOTOR_BIKE')], max_length=2)),
                ('plate_number', models.CharField(max_length=200)),
                ('driver_license', models.CharField(max_length=235)),
                ('color_of_transportation', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.administrator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=235)),
                ('pick_up_name', models.CharField(max_length=200)),
                ('pick_up_address', models.TextField(db_column='pick_up_location')),
                ('receiver_address', models.TextField(db_column='receiver_location')),
                ('package_description', models.TextField(db_column='description')),
                ('vehicle_type', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=200, unique=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rider')),
            ],
        ),
    ]
