# Generated by Django 5.0.1 on 2024-01-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='plate_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
