# Generated by Django 5.0.1 on 2024-01-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_administrator_email_remove_administrator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
